{% set name = "mytestpackage" %}
{% set version = "1.2.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2b624cf3b43032116adfdd47fd268aabcf9db6e90e7a501535f456f9e40f56f4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - mytestpackage
    - mytestpackage.group1

about:
  home: https://github.com/user/mytestpackage
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: A short description of the python package.
  description: See the README.md file on GitHub for more information.
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''

